[[redirects]]
  from = "/"
  to = "https://webruden.tistory.com"
  status = 301

[[redirects]]
  from = "/blog/vue-js-event-bus-event-bus-in-vue-js"
  to = "https://webruden.tistory.com/109"
  status = 301
  
[[redirects]]
  from = "/blog/copy-folder-in-linux"
  to = "https://webruden.tistory.com/125"
  status = 301

[[redirects]]
  from = "/blog/javascript-async-programming-callback-function"
  to = "https://webruden.tistory.com/126"
  status = 301

[[redirects]]
  from = "/blog/prime-number-in-javascript"
  to = "https://webruden.tistory.com/127"
  status = 301

[[redirects]]
  from = "/blog/fibonacci-in-javascript"
  to = "https://webruden.tistory.com/203"
  status = 301
  
[[redirects]]
  from = "/blog/inline-vs-block-vs-inline-block"
  to = "https://webruden.tistory.com/135"
  status = 301
  
[[redirects]]
  from = "/blog/deploy-vue-app-to-aws-s3"
  to = "https://webruden.tistory.com/115"
  status = 301

[[redirects]]
  from = "/tags"
  to = "https://webruden.tistory.com/tags"
  status = 301